name: Create Alfred Workflow

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:  # 允许手动触发

# 添加权限配置
permissions:
  contents: write
  packages: write
  issues: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # 获取完整历史

      - name: Build Alfred workflow
        id: builder
        uses: almibarss/build-alfred-workflow@v1
        with:
          workflow_dir: .  # 改为当前目录
          exclude_patterns: '*.pyc *__pycache__/* .git/* .github/* .vscode/* dist/* temp_workflow/*'
          custom_version: ${{ github.ref_name }}
          workflow_name: "Alfred-Common-Text-Operations"

      - name: Create Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN || secrets.GITHUB_TOKEN }}
        with:
          files: ${{ steps.builder.outputs.workflow_file }}
          name: Release ${{ github.ref_name }}
          body: |
            ## Alfred Common Text Operations ${{ github.ref_name }}
            
            ### 功能特性
            - 括号转换 (英文 ↔ 中文)
            - 数字格式化 (千分位分隔符)
            - LaTeX文本处理
            - Markdown文本处理
            - Mermaid代码处理
            
            ### 安装方法
            1. 下载 `Alfred-Common-Text-Operations.alfredworkflow`
            2. 双击文件安装到Alfred
            3. 使用universal action 调用
            
            ### 更新日志
            - 重构代码结构，提高可维护性
            - 模块化设计，易于扩展
            - 统一接口，更好的用户体验